# Generated by Django 2.0.2 on 2018-05-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryF',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '一级类别',
                'verbose_name_plural': '一级类别',
            },
        ),
        migrations.CreateModel(
            name='CatagoryS',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='类别名')),
                ('cata_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commoditys.CatagoryF', verbose_name='上级类别')),
            ],
            options={
                'verbose_name': '二级类别',
                'verbose_name_plural': '二级类别',
            },
        ),
        migrations.CreateModel(
            name='CatagoryT',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='类别名')),
                ('cata_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commoditys.CatagoryS', verbose_name='上级类别')),
            ],
            options={
                'verbose_name': '三级类别',
                'verbose_name_plural': '三级类别',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('stock', models.IntegerField(default=0, verbose_name='库存量')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('desc', models.TextField(verbose_name='简述')),
                ('catalog', models.TextField(verbose_name='目录')),
                ('image', models.ImageField(upload_to='commodity/%Y/%m', verbose_name='图片')),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commoditys.CatagoryT', verbose_name='类别')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
