# Generated by Django 2.0.2 on 2018-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0002_auto_20180506_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagoryf',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
