# Generated by Django 2.0.2 on 2018-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0003_auto_20180506_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorys',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
