# Generated by Django 2.0.2 on 2018-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0004_auto_20180506_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='pubdate',
            field=models.CharField(default='2018年8月', max_length=30, verbose_name='出版月份'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='size',
            field=models.CharField(default='16开', max_length=20, verbose_name='开本'),
        ),
    ]
