# Generated by Django 2.0.2 on 2018-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0005_auto_20180506_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='catalog',
            field=models.TextField(blank=True, null=True, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='简述'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pubdate',
            field=models.CharField(blank=True, default='2018年8月', max_length=30, null=True, verbose_name='出版月份'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='size',
            field=models.CharField(blank=True, default='16开', max_length=20, null=True, verbose_name='开本'),
        ),
    ]
