# Generated by Django 2.0.2 on 2018-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0006_auto_20180506_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='sell_nums',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
