# Generated by Django 2.0.2 on 2018-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0007_commodity_sell_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='is_sale',
            field=models.CharField(choices=[('in', '在售'), ('out', '下架')], default='in', max_length=10, verbose_name='销售状态'),
        ),
    ]
