# Generated by Django 2.0.2 on 2018-05-07 09:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LackCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='填写时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登记用户')),
            ],
            options={
                'verbose_name': '缺货登记',
                'verbose_name_plural': '缺货登记',
            },
        ),
    ]
