# Generated by Django 2.0.2 on 2018-05-12 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commoditys', '0007_commodity_sell_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opreation', '0003_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='评分')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commoditys.Commodity', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
    ]
