# Generated by Django 2.0.2 on 2018-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreation', '0004_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='is_anon',
            field=models.BooleanField(default=False, verbose_name='是否匿名'),
        ),
    ]
