# Generated by Django 2.0.2 on 2018-05-10 14:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20180508_1557'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commoditys', '0007_commodity_sell_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='出货单号')),
                ('nums', models.IntegerField(default=1, verbose_name='购买数量')),
                ('status', models.CharField(choices=[('ing', '出货中'), ('ed', '已出货')], max_length=5, verbose_name='出货情况')),
                ('tracking', models.CharField(blank=True, max_length=16, null=True, verbose_name='快递单号')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Address', verbose_name='发货地址')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commoditys.Commodity', verbose_name='商品')),
            ],
            options={
                'verbose_name': '出货单',
                'verbose_name_plural': '出货单',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '已支付'), ('fininshed', '已完成')], max_length=11, verbose_name='订单状态')),
                ('total_price', models.FloatField(verbose_name='订单总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='所属订单'),
        ),
    ]
