# Generated by Django 2.0.2 on 2018-05-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180510_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='退单号')),
                ('type', models.CharField(choices=[('m', '仅退款'), ('mc', '退货与款')], default='m', max_length=10)),
                ('status', models.CharField(choices=[('accept', '同意退货'), ('reject', '拒绝退款')], max_length=7, verbose_name='退货审核')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='退货原因')),
                ('return_status', models.CharField(blank=True, choices=[('un', '未退回'), ('ing', '已退回'), ('ed', '已退货')], max_length=6, null=True)),
                ('return_tracking', models.CharField(blank=True, max_length=16, null=True, verbose_name='退货快递单号')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryOrder', verbose_name='出货单')),
            ],
            options={
                'verbose_name': '退货单',
                'verbose_name_plural': '退货单',
            },
        ),
    ]
