# Generated by Django 2.0.2 on 2018-06-02 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_returnorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='退单号')),
                ('Company', models.CharField(default='顺丰', max_length=20, verbose_name='快递企业')),
                ('reciever', models.CharField(max_length=20, verbose_name='取件人')),
                ('track_nums', models.CharField(max_length=20, verbose_name='快递单号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物流单',
                'verbose_name_plural': '物流单',
            },
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='tracking',
        ),
        migrations.AddField(
            model_name='logistics',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryOrder', verbose_name='对应出货单'),
        ),
    ]
