# Generated by Django 2.0.2 on 2018-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180602_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='track_nums',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='快递单号'),
        ),
    ]
