# Generated by Django 2.0.2 on 2018-06-02 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180602_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间'),
        ),
    ]
