# Generated by Django 2.0.2 on 2018-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_returnorder_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='type',
            field=models.CharField(choices=[('m', '仅退款'), ('mc', '退货与款')], default='m', max_length=10, verbose_name='退货类型'),
        ),
    ]
