# Generated by Django 2.0.2 on 2018-06-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180602_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnorder',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='ReturnOrder',
        ),
    ]
