# Generated by Django 2.0.2 on 2018-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='re_status',
            field=models.CharField(blank=True, choices=[('un', '未退回'), ('ing', '退回中'), ('ed', '已退回')], max_length=10, null=True, verbose_name='退货状态'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('ing', '审核中'), ('accept', '同意退款'), ('reject', '拒绝退款')], default='ing', max_length=10, verbose_name='状态'),
        ),
    ]
