# Generated by Django 2.0.2 on 2018-06-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180602_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
