# Generated by Django 2.0.2 on 2018-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paypass',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='支付密码'),
        ),
    ]
