# Generated by Django 2.0.2 on 2018-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_paypass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forgetpwd', '忘记密码'), ('modifyemail', '修改邮箱')], max_length=20, verbose_name='用途'),
        ),
    ]
