# Generated by Django 2.0.2 on 2018-05-07 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180507_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30, verbose_name='省')),
                ('city', models.CharField(max_length=30, verbose_name='市')),
                ('region', models.CharField(blank=True, max_length=30, null=True, verbose_name='区/县')),
                ('town', models.CharField(blank=True, max_length=40, null=True, verbose_name='乡镇/街道')),
                ('detail', models.CharField(max_length=200, verbose_name='具体地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='加入时间')),
                ('name', models.CharField(max_length=20, verbose_name='联系人姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='联系方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
    ]
