# Generated by Django 2.0.2 on 2018-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forgetpwd', '忘记密码'), ('modifyemail', '修改邮箱'), ('modifypaypwd', '修改支付密码')], max_length=20, verbose_name='用途'),
        ),
    ]
