# Generated by Django 2.0.2 on 2018-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180508_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='paypass',
            field=models.CharField(blank=True, max_length=257, null=True, verbose_name='支付密码'),
        ),
    ]
