# Generated by Django 2.0.2 on 2018-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='booklist/%Y/%m', verbose_name='封面'),
        ),
    ]
