# Generated by Django 2.0.2 on 2018-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_booklist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='is_pub',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='tag2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='标签二'),
        ),
    ]
