# Generated by Django 2.0.2 on 2018-06-01 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_auto_20180601_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='booklistdetail',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
    ]
