# Generated by Django 2.0.2 on 2018-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_userfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏'),
        ),
    ]
