# Generated by Django 2.0.2 on 2018-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_booklist_fav_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_nums',
            field=models.IntegerField(default=0, verbose_name='书籍数'),
        ),
    ]
